"use client";

import * as React from "react";
import { Info } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { PageWrapper, Section, Container, Flex } from "@/components/layout/Layouts";
import { SearchBar } from "@/components/shared/SearchBar";
import { SortDropdown } from "@/components/shared/SortDropdown";
import { Pagination } from "@/components/shared/Pagination";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { useDebounce } from "@/hooks/useDebounce";
import { useRoadmaps } from "@/hooks/useRoadmaps";

export default function ExplorePage() {
  const router = useRouter();

  // API State tracking
  const [currentPage, setCurrentPage] = React.useState(1);
  const [searchVal, setSearchVal] = React.useState("");
  const [sortVal, setSortVal] = React.useState("newest");

  // Sync category parameter from routing context (e.g. Featured Path homepage click)
  const searchParams = useSearchParams();
  const categoryParam = searchParams.get("category");

  // Debounced search query tracker
  const debouncedSearch = useDebounce(searchVal, 400);

  // TanStack Query custom hook integration
  const { data, isLoading, isError, refetch } = useRoadmaps({
    page: currentPage,
    limit: 12,
    search: debouncedSearch,
    category: categoryParam || undefined,
    sort: sortVal,
  });

  // Derived state options
  const roadmaps = data?.roadmaps || [];
  const totalPages = data?.pagination.pages || 1;
  const totalResults = data?.pagination.total || 0;

  const showSkeletons = isLoading;
  const showEmptyState = roadmaps.length === 0 && !isLoading && !isError;

  return (
    <PageWrapper className="bg-slate-50 dark:bg-[#090d16] select-none min-h-screen">
      
      {/* Page Header */}
      <div className="bg-white dark:bg-[#090d16] py-10 border-b border-border-color dark:border-slate-800/30">
        <Container>
          <div className="flex flex-col gap-2.5 max-w-2xl">
            <h1 className="text-2xl font-black text-dark-text md:text-3xl lg:text-4xl tracking-tight leading-tight">
              Explore Learning Roadmaps
            </h1>
            <p className="text-xs text-secondary-text leading-relaxed">
              Find customized career pathways, generated by tech veterans and refined by artificial intelligence, to guide your developer transition.
            </p>
          </div>
        </Container>
      </div>

      <Section className="py-8 md:py-10">
        <Container>
          
          {/* ================= Top controls row ================= */}
          <div className="flex flex-col md:flex-row items-stretch md:items-center justify-between gap-4 mb-6">
            
            {/* Search Input */}
            <div className="flex-1 max-w-md">
              <SearchBar
                onSearch={(query) => {
                  setSearchVal(query);
                  setCurrentPage(1);
                }}
              />
            </div>

            {/* Sorting Dropdown */}
            <Flex align="center" gap={3} className="w-full md:w-auto">
              <SortDropdown
                value={sortVal}
                onChange={(val) => {
                  setSortVal(val);
                  setCurrentPage(1);
                }}
              />
            </Flex>
          </div>

          {/* Results count label */}
          <div className="flex items-center justify-between border-b border-border-color dark:border-slate-800/40 pb-4 mb-6">
            <span className="text-xs font-bold text-secondary-text">
              {isError ? "Error loading roadmaps" : showEmptyState ? "Showing 0 matches" : `Showing ${totalResults} career paths matched`}
            </span>
          </div>

          {/* ================= Main Layout Content Grid ================= */}
          <div className="flex flex-col gap-8 w-full">
            
            {/* Dynamic Error / Empty / Skeletons / Cards Content */}
            {isError ? (
              <div className="py-16 flex flex-col items-center gap-4 text-center max-w-md mx-auto">
                <div className="h-12 w-12 rounded-full bg-red-50 dark:bg-red-950/20 text-red-500 flex items-center justify-center font-bold text-xl">!</div>
                <h3 className="text-sm font-black text-dark-text uppercase">Connection Error</h3>
                <p className="text-xxs text-secondary-text leading-relaxed">
                  We encountered an issue retrieving our career path roadmap data from the backend server.
                </p>
                <Button
                  variant="primary"
                  size="medium"
                  onClick={() => refetch()}
                  className="text-xs font-bold px-6 py-2"
                >
                  Retry Load
                </Button>
              </div>
            ) : showEmptyState ? (
              /* Empty state render */
              <Card
                isEmpty={true}
                emptyIcon={Info}
                emptyTitle="No Roadmaps Found"
                emptyDescription="We couldn't find any career roadmaps matching your active search query or filters. Clear search input and try again."
                className="py-16 border-dashed border-border-color dark:border-slate-800/50"
              />
            ) : (
              /* Card List grid */
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                {showSkeletons ? (
                  // Render 8 skeleton cards
                  Array.from({ length: 8 }).map((_, idx) => (
                    <div key={idx} className="flex flex-col h-full w-full">
                      <Card
                        isSkeleton={true}
                        className="h-full border-border-color/60 dark:border-slate-800/40"
                      />
                    </div>
                  ))
                ) : (
                  // Render loaded MongoDB roadmaps
                  roadmaps.map((roadmap) => (
                    <Link href={`/explore/${roadmap.slug}`} key={roadmap._id} className="flex flex-col h-full w-full">
                      <Card
                        isSkeleton={false}
                        imageSrc={roadmap.coverImage}
                        imageAlt={roadmap.title}
                        title={roadmap.title}
                        description={roadmap.shortDescription}
                        metadata={[roadmap.difficulty, roadmap.duration, `★ ${roadmap.rating.toFixed(1)}`, roadmap.category]}
                        actionLabel="View Details"
                        className="h-full cursor-pointer border-border-color/60 dark:border-slate-800/40"
                      />
                    </Link>
                  ))
                )}
              </div>
            )}

            {/* ================= Pagination Section ================= */}
            {!showEmptyState && !isError && (
              <Pagination
                currentPage={currentPage}
                totalPages={totalPages}
                onPageChange={(page) => {
                  setCurrentPage(page);
                  window.scrollTo({ top: 0, behavior: "smooth" });
                }}
              />
            )}

          </div>

        </Container>
      </Section>

    </PageWrapper>
  );
}
