"use client";

import * as React from "react";
import { SlidersHorizontal, X, Info } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { useRouter, useSearchParams } from "next/navigation";
import { PageWrapper, Section, Container, Flex } from "@/components/layout/Layouts";
import { SearchBar } from "@/components/shared/SearchBar";
import { FilterPanel } from "@/components/shared/FilterPanel";
import { SortDropdown } from "@/components/shared/SortDropdown";
import { Pagination } from "@/components/shared/Pagination";
import { Card } from "@/components/ui/Card";
import { toast } from "react-hot-toast";
import { cn } from "@/utils/cn";
import { useDebounce } from "@/hooks/useDebounce";
import { useRoadmaps } from "@/hooks/useRoadmaps";

export default function ExplorePage() {
  const router = useRouter();
  // Mobile drawer filter visibility state
  const [isFilterDrawerOpen, setIsFilterDrawerOpen] = React.useState(false);
  
  // Desktop sidebar visibility state (toggles layout between 3 and 4 columns grid!)
  const [showDesktopFilters, setShowDesktopFilters] = React.useState(true);

  // Mock State Toggles (for visual reviews)
  const [isSkeleton, setIsSkeleton] = React.useState(false);
  const [isEmpty, setIsEmpty] = React.useState(false);

  // API State tracking
  const [currentPage, setCurrentPage] = React.useState(1);
  const [searchVal, setSearchVal] = React.useState("");
  const [sortVal, setSortVal] = React.useState("newest");
  const [selectedCategories, setSelectedCategories] = React.useState<string[]>([]);
  const [selectedDifficulties, setSelectedDifficulties] = React.useState<string[]>([]);

  // Sync category parameter from routing context (e.g. Featured Path homepage click)
  const searchParams = useSearchParams();
  const categoryParam = searchParams.get("category");

  React.useEffect(() => {
    if (categoryParam) {
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setSelectedCategories([categoryParam]);
    }
  }, [categoryParam]);

  // Debounced search query tracker
  const debouncedSearch = useDebounce(searchVal, 400);

  // TanStack Query custom hook integration
  const { data, isLoading, isError } = useRoadmaps({
    page: currentPage,
    limit: 12,
    search: debouncedSearch,
    category: selectedCategories.join(","),
    difficulty: selectedDifficulties.join(","),
    sort: sortVal,
  });

  // Derived state options
  const roadmaps = data?.roadmaps || [];
  const totalPages = data?.pagination.pages || 1;
  const totalResults = data?.pagination.total || 0;

  const showSkeletons = isSkeleton || isLoading;
  const showEmptyState = isEmpty || (roadmaps.length === 0 && !isLoading) || isError;



  return (
    <PageWrapper className="bg-slate-50 dark:bg-[#090d16] select-none min-h-screen">
      
      {/* Page Header */}
      <div className="bg-white dark:bg-[#090d16] py-10 border-b border-border-color dark:border-slate-800/30">
        <Container>
          <Flex justify="between" align="end" className="flex-wrap gap-4">
            <div className="flex flex-col gap-2.5 max-w-2xl">
              <h1 className="text-2xl font-black text-dark-text md:text-3xl lg:text-4xl tracking-tight leading-tight">
                Explore Learning Roadmaps
              </h1>
              <p className="text-xs text-secondary-text leading-relaxed">
                Find customized career pathways, generated by tech veterans and refined by artificial intelligence, to guide your developer transition.
              </p>
            </div>
            
            {/* Visual Review Toggles */}
            <Flex gap={3} className="bg-slate-50 dark:bg-slate-900 border border-border-color dark:border-slate-850 px-4 py-2 rounded-xl shadow-xxs flex-wrap">
              <Flex align="center" gap={2}>
                <span className="text-[10px] font-bold text-secondary-text">Skeletons:</span>
                <button
                  onClick={() => {
                    setIsSkeleton((prev) => !prev);
                    setIsEmpty(false);
                  }}
                  className={cn("relative inline-flex h-4.5 w-8 shrink-0 cursor-pointer rounded-full transition-colors duration-200 focus:outline-none", isSkeleton ? "bg-primary" : "bg-slate-200 dark:bg-slate-700")}
                >
                  <span className={cn("pointer-events-none inline-block h-3.5 w-3.5 transform rounded-full bg-white shadow-xs transition duration-200 ease-in-out mt-[2px] ml-[2px]", isSkeleton ? "translate-x-3.5" : "translate-x-0")} />
                </button>
              </Flex>
              <div className="w-[1px] bg-border-color dark:bg-slate-800 h-4" />
              <Flex align="center" gap={2}>
                <span className="text-[10px] font-bold text-secondary-text">Empty State:</span>
                <button
                  onClick={() => {
                    setIsEmpty((prev) => !prev);
                    setIsSkeleton(false);
                  }}
                  className={cn("relative inline-flex h-4.5 w-8 shrink-0 cursor-pointer rounded-full transition-colors duration-200 focus:outline-none", isEmpty ? "bg-primary" : "bg-slate-200 dark:bg-slate-700")}
                >
                  <span className={cn("pointer-events-none inline-block h-3.5 w-3.5 transform rounded-full bg-white shadow-xs transition duration-200 ease-in-out mt-[2px] ml-[2px]", isEmpty ? "translate-x-3.5" : "translate-x-0")} />
                </button>
              </Flex>
            </Flex>
          </Flex>
        </Container>
      </div>

      <Section className="py-8 md:py-10">
        <Container>
          
          {/* ================= Top controls row ================= */}
          <div className="flex flex-col md:flex-row items-stretch md:items-center justify-between gap-4 mb-6">
            
            {/* Search Input */}
            <div className="flex-1 max-w-md">
              <SearchBar
                onSearch={(query) => {
                  setSearchVal(query);
                  setCurrentPage(1);
                }}
              />
            </div>

            {/* Sorting Dropdown & Desktop filters toggler */}
            <Flex align="center" gap={3} className="w-full md:w-auto">
              
              {/* Desktop Filters Toggle Button */}
              <button
                type="button"
                onClick={() => {
                  setShowDesktopFilters((prev) => !prev);
                  // Sync mobile menu drawer if screen wraps
                  setIsFilterDrawerOpen(false);
                }}
                className="hidden md:flex h-10 items-center justify-center gap-2 rounded-lg border border-border-color dark:border-slate-800 bg-white dark:bg-slate-900 px-4 text-xs font-bold text-dark-text hover:bg-slate-50 dark:hover:bg-slate-800/20 transition-all select-none"
              >
                <SlidersHorizontal className="h-4 w-4 text-secondary-text" />
                <span>{showDesktopFilters ? "Hide Filters" : "Show Filters"}</span>
              </button>

              {/* Sort Select components */}
              <SortDropdown
                value={sortVal}
                onChange={(val) => {
                  setSortVal(val);
                  setCurrentPage(1);
                }}
              />

              {/* Mobile Filter Button toggle */}
              <button
                type="button"
                onClick={() => setIsFilterDrawerOpen(true)}
                className="md:hidden flex h-10 items-center justify-center gap-2 rounded-lg border border-border-color dark:border-slate-800 bg-white dark:bg-slate-900 px-4 text-xs font-bold text-dark-text hover:bg-slate-50 dark:hover:bg-slate-800/20 transition-all select-none"
              >
                <SlidersHorizontal className="h-4 w-4 text-secondary-text" />
                <span>Filters</span>
              </button>
            </Flex>
          </div>

          {/* Results count label */}
          <div className="flex items-center justify-between border-b border-border-color dark:border-slate-800/40 pb-4 mb-6">
            <span className="text-xs font-bold text-secondary-text">
              {showEmptyState ? "Showing 0 matches" : `Showing ${totalResults} career paths matched`}
            </span>
          </div>

          {/* ================= Main Layout Content Grid ================= */}
          <div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-start">
            
            {/* Desktop Filter Sidebar Column (Span 3) */}
            {showDesktopFilters && (
              <aside className="hidden md:block md:col-span-3 bg-white dark:bg-[#090d16] border border-border-color dark:border-slate-800/40 p-6 rounded-xl shadow-xs">
                <FilterPanel
                  onApply={(filters) => {
                    setSelectedCategories(filters.categories);
                    setSelectedDifficulties(filters.difficulties);
                    setCurrentPage(1);
                    toast.success("Filters applied successfully!", {
                      id: "filter-apply-toast",
                    });
                  }}
                  onReset={() => {
                    setSelectedCategories([]);
                    setSelectedDifficulties([]);
                    setCurrentPage(1);
                    toast.success("Filters cleared successfully!", {
                      id: "filter-reset-toast",
                    });
                  }}
                />
              </aside>
            )}

            {/* Results Grid Column (Span 9 or 12) */}
            <main className={cn(showDesktopFilters ? "md:col-span-9" : "md:col-span-12", "flex flex-col gap-8")}>
              
              {/* Dynamic Empty / Skeletons / Cards Content */}
              {showEmptyState ? (
                /* Empty state render */
                <Card
                  isEmpty={true}
                  emptyIcon={Info}
                  emptyTitle="No Roadmaps Found"
                  emptyDescription="We couldn't find any career roadmaps matching your active filter configuration. Clear checkboxes and try again."
                  className="py-16 border-dashed border-border-color dark:border-slate-800/50"
                />
              ) : (
                /* Card List grid */
                <div
                  className={cn(
                    "grid grid-cols-1 gap-5",
                    "sm:grid-cols-2",
                    showDesktopFilters ? "lg:grid-cols-3" : "lg:grid-cols-4"
                  )}
                >
                  {showSkeletons ? (
                    // Render 6 skeleton cards
                    Array.from({ length: 6 }).map((_, idx) => (
                      <div key={idx} className="flex flex-col h-full w-full">
                        <Card
                          isSkeleton={true}
                          imageSrc=""
                          imageAlt=""
                          title=""
                          description=""
                          metadata={[]}
                          actionLabel=""
                          className="h-full border-border-color/60 dark:border-slate-800/40"
                        />
                      </div>
                    ))
                  ) : (
                    // Render loaded MongoDB roadmaps
                    roadmaps.map((roadmap) => (
                      <div key={roadmap._id} className="flex flex-col h-full w-full">
                        <Card
                          isSkeleton={false}
                          imageSrc={roadmap.coverImage}
                          imageAlt={roadmap.title}
                          title={roadmap.title}
                          description={roadmap.shortDescription}
                          metadata={[roadmap.difficulty, roadmap.duration, `★ ${roadmap.rating.toFixed(1)}`, roadmap.category]}
                          actionLabel="View Details"
                          onAction={() => router.push(`/explore/${roadmap.slug}`)}
                          className="h-full border-border-color/60 dark:border-slate-800/40"
                        />
                      </div>
                    ))
                  )}
                </div>
              )}

              {/* ================= Pagination Section Placeholder ================= */}
              {!showEmptyState && (
                <Pagination
                  currentPage={currentPage}
                  totalPages={totalPages}
                  onPageChange={(page) => {
                    setCurrentPage(page);
                    window.scrollTo({ top: 0, behavior: "smooth" });
                  }}
                />
              )}

            </main>
          </div>

        </Container>
      </Section>

      {/* ================= Mobile Filter Drawer Overlay ================= */}
      <AnimatePresence>
        {isFilterDrawerOpen && (
          <>
            {/* Backdrop layer */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setIsFilterDrawerOpen(false)}
              className="fixed inset-0 bg-slate-950/40 backdrop-blur-xs z-50 md:hidden"
            />

            {/* Sidebar drawer panel */}
            <motion.div
              initial={{ x: "100%" }}
              animate={{ x: 0 }}
              exit={{ x: "100%" }}
              transition={{ type: "spring", stiffness: 380, damping: 30 }}
              className="fixed right-0 top-0 bottom-0 w-80 bg-white dark:bg-[#090d16] shadow-xl z-55 p-6 flex flex-col gap-5 overflow-y-auto md:hidden"
            >
              <div className="flex justify-end border-b border-border-color dark:border-slate-800 pb-3">
                <button
                  type="button"
                  onClick={() => setIsFilterDrawerOpen(false)}
                  className="p-1.5 rounded-md hover:bg-slate-100 dark:hover:bg-slate-850 text-secondary-text hover:text-dark-text transition-all"
                  aria-label="Close filters panel"
                >
                  <X className="h-4.5 w-4.5" />
                </button>
              </div>

              <FilterPanel
                onApply={(filters) => {
                  setSelectedCategories(filters.categories);
                  setSelectedDifficulties(filters.difficulties);
                  setCurrentPage(1);
                  setIsFilterDrawerOpen(false);
                  toast.success("Filters applied successfully!", {
                    id: "filter-apply-toast",
                  });
                }}
                onReset={() => {
                  setSelectedCategories([]);
                  setSelectedDifficulties([]);
                  setCurrentPage(1);
                  setIsFilterDrawerOpen(false);
                  toast.success("Filters cleared successfully!", {
                    id: "filter-reset-toast",
                  });
                }}
              />
            </motion.div>
          </>
        )}
      </AnimatePresence>

    </PageWrapper>
  );
}
